export enum ErrorCode {
    FOOD_NOT_FOUND = "FOOD_NOT_FOUND",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    PASSWORD_INVALID = "PASSWORD_INVALID",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
